using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using TMPro;

public class GameManager : MonoBehaviour
{
    public int score = 0;
    public TextMeshProUGUI scoreText;

    void Start()
    {
        
    }

    void Update()
    {
        
    }

    void OnCollisionEnter(Collision collision)
    {
        if (collision.gameObject.CompareTag("Target"))
        {
            // W[oだ
            score += 100;
            // 蠓soだ陪ボ
            scoreText.text = "Score: " + score.ToString();
            // 冀癍诞末尾嗓l莫G单
        }
        else if (collision.gameObject.CompareTag("Obstacle"))
        {
            // 搭ぶネR┪ㄤLB@
            // 冀癍诞末尾嗓l莫G单
        }
    }
}
